# [AdventureWorks]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [AdventureWorks]    Script Date: 25-05-2023 18:33:48 ******/
CREATE DATABASE [AdventureWorks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorksDW2017', FILENAME = N'/var/opt/mssql/data/f7579300-91e8-43d5-bd8f-21b6a56f37ff_AdventureWorksDW2017.mdf' , SIZE = 4399104KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdventureWorksDW2017_log', FILENAME = N'/var/opt/mssql/data/f7579300-91e8-43d5-bd8f-21b6a56f37ff_AdventureWorksDW2017_log.ldf' , SIZE = 5382144KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [AdventureWorks] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AdventureWorks] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AdventureWorks] SET ANSI_NULLS ON 
GO
ALTER DATABASE [AdventureWorks] SET ANSI_PADDING ON 
GO
ALTER DATABASE [AdventureWorks] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [AdventureWorks] SET ARITHABORT ON 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AdventureWorks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AdventureWorks] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AdventureWorks] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [AdventureWorks] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AdventureWorks] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [AdventureWorks] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AdventureWorks] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AdventureWorks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AdventureWorks] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AdventureWorks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AdventureWorks] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AdventureWorks] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AdventureWorks] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AdventureWorks] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AdventureWorks] SET  MULTI_USER 
GO
ALTER DATABASE [AdventureWorks] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AdventureWorks] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AdventureWorks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AdventureWorks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AdventureWorks] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AdventureWorks', N'ON'
GO
ALTER DATABASE [AdventureWorks] SET QUERY_STORE = ON
GO
ALTER DATABASE [AdventureWorks] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [poc_user]

In [0]:
USE [AdventureWorks]
GO

In [0]:
/****** Object:  User [poc_user]    Script Date: 25-05-2023 18:33:53 ******/
CREATE USER [poc_user] FOR LOGIN [poc_user] WITH DEFAULT_SCHEMA=[dbo]
GO

In [0]:
ALTER ROLE [db_datareader] ADD MEMBER [poc_user]
GO

# [dbo].[account_id]

In [0]:
/****** Object:  UserDefinedDataType [dbo].[account_id]    Script Date: 25-05-2023 18:33:53 ******/
CREATE TYPE [dbo].[account_id] FROM [int] NULL
GO

# [dbo].[mobile]

In [0]:
/****** Object:  UserDefinedDataType [dbo].[mobile]    Script Date: 25-05-2023 18:33:53 ******/
CREATE TYPE [dbo].[mobile] FROM [varchar](10) NULL
GO

# [dbo].[Pincode]

In [0]:
/****** Object:  UserDefinedDataType [dbo].[Pincode]    Script Date: 25-05-2023 18:33:53 ******/
CREATE TYPE [dbo].[Pincode] FROM [varchar](6) NOT NULL
GO

# [dbo].[currency]

In [0]:
/****** Object:  Synonym [dbo].[currency]    Script Date: 25-05-2023 18:33:53 ******/
CREATE SYNONYM [dbo].[currency] FOR [AdventureWorks].[dbo].[DimCurrency]
GO

# [dbo].[udfBuildISO8601Date]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[udfBuildISO8601Date]    Script Date: 25-05-2023 18:33:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



-- ******************************************************
-- Create User Defined Functions
-- ******************************************************
-- Builds an ISO 8601 format date from a year, month, and day specified as integers.
-- This format of date should parse correctly regardless of SET DATEFORMAT and SET LANGUAGE.
-- See SQL Server Books Online for more details.
CREATE FUNCTION [dbo].[udfBuildISO8601Date] (@year int, @month int, @day int)
RETURNS datetime
AS 
BEGIN
	RETURN cast(convert(varchar, @year) + '-' + [dbo].[udfTwoDigitZeroFill](@month) 
	    + '-' + [dbo].[udfTwoDigitZeroFill](@day) + 'T00:00:00' 
	    as datetime);
END;
GO

# [dbo].[udfMinimumDate]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[udfMinimumDate]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[udfMinimumDate] (
    @x DATETIME, 
    @y DATETIME
) RETURNS DATETIME
AS
BEGIN
    DECLARE @z DATETIME

    IF @x <= @y 
        SET @z = @x 
    ELSE 
        SET @z = @y

    RETURN(@z)
END;
GO

# [dbo].[udfTwoDigitZeroFill]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[udfTwoDigitZeroFill]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Converts the specified integer (which should be < 100 and > -1)
-- into a two character string, zero filling from the left 
-- if the number is < 10.
CREATE FUNCTION [dbo].[udfTwoDigitZeroFill] (@number int) 
RETURNS char(2)
AS
BEGIN
	DECLARE @result char(2);
	IF @number > 9 
		SET @result = convert(char(2), @number);
	ELSE
		SET @result = convert(char(2), '0' + convert(varchar, @number));
	RETURN @result;
END;
GO

# [dbo].[DimAccount]

In [0]:
/****** Object:  Table [dbo].[DimAccount]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimAccount](
	[AccountKey] [int] IDENTITY(1,1) NOT NULL,
	[ParentAccountKey] [int] NULL,
	[AccountCodeAlternateKey] [int] NULL,
	[ParentAccountCodeAlternateKey] [int] NULL,
	[AccountDescription] [nvarchar](50) NULL,
	[AccountType] [nvarchar](50) NULL,
	[Operator] [nvarchar](50) NULL,
	[CustomMembers] [nvarchar](300) NULL,
	[ValueType] [nvarchar](50) NULL,
	[CustomMemberOptions] [nvarchar](200) NULL,
 CONSTRAINT [PK_DimAccount] PRIMARY KEY CLUSTERED 
(
	[AccountKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[udfGetProductList]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[udfGetProductList]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[udfGetProductList]
(@AccountKey SMALLINT
)
RETURNS TABLE
AS
RETURN
(SELECT *
from [dbo].[DimAccount]
 WHERE AccountKey >=@AccountKey )
GO

# [dbo].[DimCustomer]

In [0]:
/****** Object:  Table [dbo].[DimCustomer]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimCustomer](
	[CustomerKey] [int] IDENTITY(1,1) NOT NULL,
	[GeographyKey] [int] NULL,
	[CustomerAlternateKey] [nvarchar](15) NOT NULL,
	[Title] [nvarchar](8) NULL,
	[FirstName] [nvarchar](50) NULL,
	[MiddleName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[NameStyle] [bit] NULL,
	[BirthDate] [date] NULL,
	[MaritalStatus] [nchar](1) NULL,
	[Suffix] [nvarchar](10) NULL,
	[Gender] [nvarchar](1) NULL,
	[EmailAddress] [nvarchar](50) NULL,
	[YearlyIncome] [money] NULL,
	[TotalChildren] [tinyint] NULL,
	[NumberChildrenAtHome] [tinyint] NULL,
	[EnglishEducation] [nvarchar](40) NULL,
	[SpanishEducation] [nvarchar](40) NULL,
	[FrenchEducation] [nvarchar](40) NULL,
	[EnglishOccupation] [nvarchar](100) NULL,
	[SpanishOccupation] [nvarchar](100) NULL,
	[FrenchOccupation] [nvarchar](100) NULL,
	[HouseOwnerFlag] [nchar](1) NULL,
	[NumberCarsOwned] [tinyint] NULL,
	[AddressLine1] [nvarchar](120) NULL,
	[AddressLine2] [nvarchar](120) NULL,
	[Phone] [nvarchar](20) NULL,
	[DateFirstPurchase] [date] NULL,
	[CommuteDistance] [nvarchar](15) NULL,
 CONSTRAINT [PK_DimCustomer_CustomerKey] PRIMARY KEY CLUSTERED 
(
	[CustomerKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimDate]

In [0]:
/****** Object:  Table [dbo].[DimDate]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimDate](
	[DateKey] [int] NOT NULL,
	[FullDateAlternateKey] [date] NOT NULL,
	[DayNumberOfWeek] [tinyint] NOT NULL,
	[EnglishDayNameOfWeek] [nvarchar](10) NOT NULL,
	[SpanishDayNameOfWeek] [nvarchar](10) NOT NULL,
	[FrenchDayNameOfWeek] [nvarchar](10) NOT NULL,
	[DayNumberOfMonth] [tinyint] NOT NULL,
	[DayNumberOfYear] [smallint] NOT NULL,
	[WeekNumberOfYear] [tinyint] NOT NULL,
	[EnglishMonthName] [nvarchar](10) NOT NULL,
	[SpanishMonthName] [nvarchar](10) NOT NULL,
	[FrenchMonthName] [nvarchar](10) NOT NULL,
	[MonthNumberOfYear] [tinyint] NOT NULL,
	[CalendarQuarter] [tinyint] NOT NULL,
	[CalendarYear] [smallint] NOT NULL,
	[CalendarSemester] [tinyint] NOT NULL,
	[FiscalQuarter] [tinyint] NOT NULL,
	[FiscalYear] [smallint] NOT NULL,
	[FiscalSemester] [tinyint] NOT NULL,
 CONSTRAINT [PK_DimDate_DateKey] PRIMARY KEY CLUSTERED 
(
	[DateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimGeography]

In [0]:
/****** Object:  Table [dbo].[DimGeography]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimGeography](
	[GeographyKey] [int] IDENTITY(1,1) NOT NULL,
	[City] [nvarchar](30) NULL,
	[StateProvinceCode] [nvarchar](3) NULL,
	[StateProvinceName] [nvarchar](50) NULL,
	[CountryRegionCode] [nvarchar](3) NULL,
	[EnglishCountryRegionName] [nvarchar](50) NULL,
	[SpanishCountryRegionName] [nvarchar](50) NULL,
	[FrenchCountryRegionName] [nvarchar](50) NULL,
	[PostalCode] [nvarchar](15) NULL,
	[SalesTerritoryKey] [int] NULL,
	[IpAddressLocator] [nvarchar](15) NULL,
 CONSTRAINT [PK_DimGeography_GeographyKey] PRIMARY KEY CLUSTERED 
(
	[GeographyKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimProduct]

In [0]:
/****** Object:  Table [dbo].[DimProduct]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProduct](
	[ProductKey] [int] IDENTITY(1,1) NOT NULL,
	[ProductAlternateKey] [nvarchar](25) NULL,
	[ProductSubcategoryKey] [int] NULL,
	[WeightUnitMeasureCode] [nchar](3) NULL,
	[SizeUnitMeasureCode] [nchar](3) NULL,
	[EnglishProductName] [nvarchar](50) NOT NULL,
	[SpanishProductName] [nvarchar](50) NOT NULL,
	[FrenchProductName] [nvarchar](50) NOT NULL,
	[StandardCost] [money] NULL,
	[FinishedGoodsFlag] [bit] NOT NULL,
	[Color] [nvarchar](15) NOT NULL,
	[SafetyStockLevel] [smallint] NULL,
	[ReorderPoint] [smallint] NULL,
	[ListPrice] [money] NULL,
	[Size] [nvarchar](50) NULL,
	[SizeRange] [nvarchar](50) NULL,
	[Weight] [float] NULL,
	[DaysToManufacture] [int] NULL,
	[ProductLine] [nchar](2) NULL,
	[DealerPrice] [money] NULL,
	[Class] [nchar](2) NULL,
	[Style] [nchar](2) NULL,
	[ModelName] [nvarchar](50) NULL,
	[LargePhoto] [varbinary](max) NULL,
	[EnglishDescription] [nvarchar](400) NULL,
	[FrenchDescription] [nvarchar](400) NULL,
	[ChineseDescription] [nvarchar](400) NULL,
	[ArabicDescription] [nvarchar](400) NULL,
	[HebrewDescription] [nvarchar](400) NULL,
	[ThaiDescription] [nvarchar](400) NULL,
	[GermanDescription] [nvarchar](400) NULL,
	[JapaneseDescription] [nvarchar](400) NULL,
	[TurkishDescription] [nvarchar](400) NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[Status] [nvarchar](7) NULL,
 CONSTRAINT [PK_DimProduct_ProductKey] PRIMARY KEY CLUSTERED 
(
	[ProductKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_DimProduct_ProductAlternateKey_StartDate] UNIQUE NONCLUSTERED 
(
	[ProductAlternateKey] ASC,
	[StartDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[DimProductCategory]

In [0]:
/****** Object:  Table [dbo].[DimProductCategory]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProductCategory](
	[ProductCategoryKey] [int] IDENTITY(1,1) NOT NULL,
	[ProductCategoryAlternateKey] [int] NULL,
	[EnglishProductCategoryName] [nvarchar](50) NOT NULL,
	[SpanishProductCategoryName] [nvarchar](50) NOT NULL,
	[FrenchProductCategoryName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DimProductCategory_ProductCategoryKey] PRIMARY KEY CLUSTERED 
(
	[ProductCategoryKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_DimProductCategory_ProductCategoryAlternateKey] UNIQUE NONCLUSTERED 
(
	[ProductCategoryAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimProductSubcategory]

In [0]:
/****** Object:  Table [dbo].[DimProductSubcategory]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProductSubcategory](
	[ProductSubcategoryKey] [int] IDENTITY(1,1) NOT NULL,
	[ProductSubcategoryAlternateKey] [int] NULL,
	[EnglishProductSubcategoryName] [nvarchar](50) NOT NULL,
	[SpanishProductSubcategoryName] [nvarchar](50) NOT NULL,
	[FrenchProductSubcategoryName] [nvarchar](50) NOT NULL,
	[ProductCategoryKey] [int] NULL,
 CONSTRAINT [PK_DimProductSubcategory_ProductSubcategoryKey] PRIMARY KEY CLUSTERED 
(
	[ProductSubcategoryKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_DimProductSubcategory_ProductSubcategoryAlternateKey] UNIQUE NONCLUSTERED 
(
	[ProductSubcategoryAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimSalesTerritory]

In [0]:
/****** Object:  Table [dbo].[DimSalesTerritory]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimSalesTerritory](
	[SalesTerritoryKey] [int] IDENTITY(1,1) NOT NULL,
	[SalesTerritoryAlternateKey] [int] NULL,
	[SalesTerritoryRegion] [nvarchar](50) NOT NULL,
	[SalesTerritoryCountry] [nvarchar](50) NOT NULL,
	[SalesTerritoryGroup] [nvarchar](50) NULL,
	[SalesTerritoryImage] [varbinary](max) NULL,
 CONSTRAINT [PK_DimSalesTerritory_SalesTerritoryKey] PRIMARY KEY CLUSTERED 
(
	[SalesTerritoryKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_DimSalesTerritory_SalesTerritoryAlternateKey] UNIQUE NONCLUSTERED 
(
	[SalesTerritoryAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[FactInternetSales]

In [0]:
/****** Object:  Table [dbo].[FactInternetSales]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactInternetSales](
	[ProductKey] [int] NOT NULL,
	[OrderDateKey] [int] NOT NULL,
	[DueDateKey] [int] NOT NULL,
	[ShipDateKey] [int] NOT NULL,
	[CustomerKey] [int] NOT NULL,
	[PromotionKey] [int] NOT NULL,
	[CurrencyKey] [int] NOT NULL,
	[SalesTerritoryKey] [int] NOT NULL,
	[SalesOrderNumber] [nvarchar](20) NOT NULL,
	[SalesOrderLineNumber] [tinyint] NOT NULL,
	[RevisionNumber] [tinyint] NOT NULL,
	[OrderQuantity] [smallint] NOT NULL,
	[UnitPrice] [money] NOT NULL,
	[ExtendedAmount] [money] NOT NULL,
	[UnitPriceDiscountPct] [float] NOT NULL,
	[DiscountAmount] [float] NOT NULL,
	[ProductStandardCost] [money] NOT NULL,
	[TotalProductCost] [money] NOT NULL,
	[SalesAmount] [money] NOT NULL,
	[TaxAmt] [money] NOT NULL,
	[Freight] [money] NOT NULL,
	[CarrierTrackingNumber] [nvarchar](25) NULL,
	[CustomerPONumber] [nvarchar](25) NULL,
	[OrderDate] [datetime] NULL,
	[DueDate] [datetime] NULL,
	[ShipDate] [datetime] NULL,
 CONSTRAINT [PK_FactInternetSales_SalesOrderNumber_SalesOrderLineNumber] PRIMARY KEY CLUSTERED 
(
	[SalesOrderNumber] ASC,
	[SalesOrderLineNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[vDMPrep]

In [0]:
/****** Object:  View [dbo].[vDMPrep]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- vDMPrep will be used as a data source by the other data mining views.  
-- Uses DW data at customer, product, day, etc. granularity and
-- gets region, model, year, month, etc.
CREATE VIEW [dbo].[vDMPrep]
AS
    SELECT
        pc.[EnglishProductCategoryName]
        ,Coalesce(p.[ModelName], p.[EnglishProductName]) AS [Model]
        ,c.[CustomerKey]
        ,s.[SalesTerritoryGroup] AS [Region]
        ,CASE
            WHEN Month(GetDate()) < Month(c.[BirthDate])
                THEN DateDiff(yy,c.[BirthDate],GetDate()) - 1
            WHEN Month(GetDate()) = Month(c.[BirthDate])
            AND Day(GetDate()) < Day(c.[BirthDate])
                THEN DateDiff(yy,c.[BirthDate],GetDate()) - 1
            ELSE DateDiff(yy,c.[BirthDate],GetDate())
        END AS [Age]
        ,CASE
            WHEN c.[YearlyIncome] < 40000 THEN 'Low'
            WHEN c.[YearlyIncome] > 60000 THEN 'High'
            ELSE 'Moderate'
        END AS [IncomeGroup]
        ,d.[CalendarYear]
        ,d.[FiscalYear]
        ,d.[MonthNumberOfYear] AS [Month]
        ,f.[SalesOrderNumber] AS [OrderNumber]
        ,f.SalesOrderLineNumber AS LineNumber
        ,f.OrderQuantity AS Quantity
        ,f.ExtendedAmount AS Amount  
    FROM
        [dbo].[FactInternetSales] f
    INNER JOIN [dbo].[DimDate] d
        ON f.[OrderDateKey] = d.[DateKey]
    INNER JOIN [dbo].[DimProduct] p
        ON f.[ProductKey] = p.[ProductKey]
    INNER JOIN [dbo].[DimProductSubcategory] psc
        ON p.[ProductSubcategoryKey] = psc.[ProductSubcategoryKey]
    INNER JOIN [dbo].[DimProductCategory] pc
        ON psc.[ProductCategoryKey] = pc.[ProductCategoryKey]
    INNER JOIN [dbo].[DimCustomer] c
        ON f.[CustomerKey] = c.[CustomerKey]
    INNER JOIN [dbo].[DimGeography] g
        ON c.[GeographyKey] = g.[GeographyKey]
    INNER JOIN [dbo].[DimSalesTerritory] s
        ON g.[SalesTerritoryKey] = s.[SalesTerritoryKey] 
;

GO

# [dbo].[vTimeSeries]

In [0]:
/****** Object:  View [dbo].[vTimeSeries]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- vTimeSeries view supports the creation of time series data mining models.
--      - Replaces earlier bike models with successor models.
--      - Abbreviates model names to improve readability in mining model viewer
--      - Concatenates model and region so that table only has one input.
--      - Creates a date field indexed to monthly reporting date for use in prediction.
CREATE VIEW [dbo].[vTimeSeries] 
AS
    SELECT 
        CASE [Model] 
            WHEN 'Mountain-100' THEN 'M200' 
            WHEN 'Road-150' THEN 'R250' 
            WHEN 'Road-650' THEN 'R750' 
            WHEN 'Touring-1000' THEN 'T1000' 
            ELSE Left([Model], 1) + Right([Model], 3) 
        END + ' ' + [Region] AS [ModelRegion] 
        ,(Convert(Integer, [CalendarYear]) * 100) + Convert(Integer, [Month]) AS [TimeIndex] 
        ,Sum([Quantity]) AS [Quantity] 
        ,Sum([Amount]) AS [Amount]
		,CalendarYear
		,[Month]
		,[dbo].[udfBuildISO8601Date] ([CalendarYear], [Month], 25)
		as ReportingDate
    FROM 
        [dbo].[vDMPrep] 
    WHERE 
        [Model] IN ('Mountain-100', 'Mountain-200', 'Road-150', 'Road-250', 
            'Road-650', 'Road-750', 'Touring-1000') 
    GROUP BY 
        CASE [Model] 
            WHEN 'Mountain-100' THEN 'M200' 
            WHEN 'Road-150' THEN 'R250' 
            WHEN 'Road-650' THEN 'R750' 
            WHEN 'Touring-1000' THEN 'T1000' 
            ELSE Left(Model,1) + Right(Model,3) 
        END + ' ' + [Region] 
        ,(Convert(Integer, [CalendarYear]) * 100) + Convert(Integer, [Month])
		,CalendarYear
		,[Month]
		,[dbo].[udfBuildISO8601Date] ([CalendarYear], [Month], 25);

GO

# [dbo].[vTargetMail]

In [0]:
/****** Object:  View [dbo].[vTargetMail]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- vTargetMail supports targeted mailing data model
-- Uses vDMPrep to determine if a customer buys a bike and joins to DimCustomer
CREATE VIEW [dbo].[vTargetMail] 
AS
    SELECT
        c.[CustomerKey], 
        c.[GeographyKey], 
        c.[CustomerAlternateKey], 
        c.[Title], 
        c.[FirstName], 
        c.[MiddleName], 
        c.[LastName], 
        c.[NameStyle], 
        c.[BirthDate], 
        c.[MaritalStatus], 
        c.[Suffix], 
        c.[Gender], 
        c.[EmailAddress], 
        c.[YearlyIncome], 
        c.[TotalChildren], 
        c.[NumberChildrenAtHome], 
        c.[EnglishEducation], 
        c.[SpanishEducation], 
        c.[FrenchEducation], 
        c.[EnglishOccupation], 
        c.[SpanishOccupation], 
        c.[FrenchOccupation], 
        c.[HouseOwnerFlag], 
        c.[NumberCarsOwned], 
        c.[AddressLine1], 
        c.[AddressLine2], 
        c.[Phone], 
        c.[DateFirstPurchase], 
        c.[CommuteDistance], 
        x.[Region], 
        x.[Age], 
        CASE x.[Bikes] 
            WHEN 0 THEN 0 
            ELSE 1 
        END AS [BikeBuyer]
    FROM
        [dbo].[DimCustomer] c INNER JOIN (
            SELECT
                [CustomerKey]
                ,[Region]
                ,[Age]
                ,Sum(
                    CASE [EnglishProductCategoryName] 
                        WHEN 'Bikes' THEN 1 
                        ELSE 0 
                    END) AS [Bikes]
            FROM
                [dbo].[vDMPrep] 
            GROUP BY
                [CustomerKey]
                ,[Region]
                ,[Age]
            ) AS [x]
        ON c.[CustomerKey] = x.[CustomerKey]
;

GO

# [dbo].[vAssocSeqOrders]

In [0]:
/****** Object:  View [dbo].[vAssocSeqOrders]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/* vAssocSeqOrders supports assocation and sequence clustering data mmining models.
      - Limits data to FY2004.
      - Creates order case table and line item nested table.*/
CREATE VIEW [dbo].[vAssocSeqOrders]
AS
SELECT DISTINCT OrderNumber, CustomerKey, Region, IncomeGroup
FROM         dbo.vDMPrep
WHERE     (FiscalYear = '2013')

GO

# [dbo].[vAssocSeqLineItems]

In [0]:
/****** Object:  View [dbo].[vAssocSeqLineItems]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vAssocSeqLineItems]
AS
SELECT     OrderNumber, LineNumber, Model
FROM         dbo.vDMPrep
WHERE     (FiscalYear = '2013')
GO

# [dbo].[DimCurrency]

In [0]:
/****** Object:  Table [dbo].[DimCurrency]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimCurrency](
	[CurrencyKey] [int] IDENTITY(1,1) NOT NULL,
	[CurrencyAlternateKey] [nchar](3) NOT NULL,
	[CurrencyName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DimCurrency_CurrencyKey] PRIMARY KEY CLUSTERED 
(
	[CurrencyKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[mv_test]

In [0]:
/****** Object:  View [dbo].[mv_test]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create   view [dbo].[mv_test] 
with schemabinding 
as 
select count_big(*) count_key, CurrencyKey,CurrencyAlternateKey
from [dbo].[DimCurrency]
group by CurrencyKey,CurrencyAlternateKey
GO

# [umv]

In [0]:
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO
/****** Object:  Index [umv]    Script Date: 25-05-2023 18:33:54 ******/
CREATE UNIQUE CLUSTERED INDEX [umv] ON [dbo].[mv_test]
(
	[CurrencyKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

# [dbo].[ActiveUserConnections]

In [0]:
/****** Object:  Table [dbo].[ActiveUserConnections]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ActiveUserConnections](
	[DBName] [nvarchar](128) NULL,
	[NumberOfConnections] [int] NULL,
	[LoginName] [nchar](128) NOT NULL
) ON [PRIMARY]
GO

# [dbo].[AdventureWorksDWBuildVersion]

In [0]:
/****** Object:  Table [dbo].[AdventureWorksDWBuildVersion]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdventureWorksDWBuildVersion](
	[DBVersion] [nvarchar](50) NULL,
	[VersionDate] [datetime] NULL
) ON [PRIMARY]
GO

# [dbo].[Constraints_Details]

In [0]:
/****** Object:  Table [dbo].[Constraints_Details]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Constraints_Details](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[CONSTRAINT_CATALOG] [nvarchar](100) NULL,
	[CONSTRAINT_SCHEMA] [nvarchar](100) NULL,
	[CONSTRAINT_NAME] [nvarchar](100) NULL,
	[TABLE_CATALOG] [nvarchar](100) NULL,
	[TABLE_SCHEMA] [nvarchar](100) NULL,
	[TABLE_NAME] [nvarchar](100) NULL,
	[CONSTRAINT_TYPE] [nvarchar](100) NULL,
	[IS_DEFERRABLE] [nvarchar](100) NULL,
	[INITIALLY_DEFERRED] [nvarchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[cost_summary]

In [0]:
/****** Object:  Table [dbo].[cost_summary]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cost_summary](
	[query_frequency] [decimal](18, 9) NULL,
	[data_returned] [decimal](18, 9) NULL,
	[data_files_size] [decimal](18, 9) NULL,
	[log_files_size] [decimal](18, 9) NULL
) ON [PRIMARY]
GO

# [dbo].[Database_Size]

In [0]:
/****** Object:  Table [dbo].[Database_Size]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Database_Size](
	[NAME] [sysname] NOT NULL,
	[Size_MBs] [bigint] NULL,
	[Size_GBs] [bigint] NULL
) ON [PRIMARY]
GO

# [dbo].[DatabaseLog]

In [0]:
/****** Object:  Table [dbo].[DatabaseLog]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatabaseLog](
	[DatabaseLogID] [int] IDENTITY(1,1) NOT NULL,
	[PostTime] [datetime] NOT NULL,
	[DatabaseUser] [sysname] NOT NULL,
	[Event] [sysname] NOT NULL,
	[Schema] [sysname] NULL,
	[Object] [sysname] NULL,
	[TSQL] [nvarchar](max) NOT NULL,
	[XmlEvent] [xml] NOT NULL,
 CONSTRAINT [PK_DatabaseLog_DatabaseLogID] PRIMARY KEY NONCLUSTERED 
(
	[DatabaseLogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[DatabaseSize]

In [0]:
/****** Object:  Table [dbo].[DatabaseSize]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatabaseSize](
	[DatabaseName] [nvarchar](128) NULL,
	[SizeInGB] [decimal](18, 9) NULL,
	[storage_cost] [decimal](18, 9) NULL
) ON [PRIMARY]
GO

# [dbo].[DatabseSize]

In [0]:
/****** Object:  Table [dbo].[DatabseSize]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatabseSize](
	[name] [nvarchar](128) NULL,
	[rows] [char](11) NULL,
	[reserved] [varchar](18) NULL,
	[data] [varchar](18) NULL,
	[index_size] [varchar](18) NULL,
	[unused] [varchar](18) NULL
) ON [PRIMARY]
GO

# [dbo].[Dependency_Details]

In [0]:
/****** Object:  Table [dbo].[Dependency_Details]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dependency_Details](
	[referencing_database] [varchar](max) NULL,
	[referencing_schema] [varchar](max) NULL,
	[referencing_object_name] [varchar](max) NULL,
	[referenced_database] [varchar](max) NULL,
	[referenced_schema] [varchar](max) NULL,
	[referenced_object_name] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[DimDepartmentGroup]

In [0]:
/****** Object:  Table [dbo].[DimDepartmentGroup]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimDepartmentGroup](
	[DepartmentGroupKey] [int] IDENTITY(1,1) NOT NULL,
	[ParentDepartmentGroupKey] [int] NULL,
	[DepartmentGroupName] [nvarchar](50) NULL,
 CONSTRAINT [PK_DimDepartmentGroup] PRIMARY KEY CLUSTERED 
(
	[DepartmentGroupKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimEmployee]

In [0]:
/****** Object:  Table [dbo].[DimEmployee]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimEmployee](
	[EmployeeKey] [int] IDENTITY(1,1) NOT NULL,
	[ParentEmployeeKey] [int] NULL,
	[EmployeeNationalIDAlternateKey] [nvarchar](15) NULL,
	[ParentEmployeeNationalIDAlternateKey] [nvarchar](15) NULL,
	[SalesTerritoryKey] [int] NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[MiddleName] [nvarchar](50) NULL,
	[NameStyle] [bit] NOT NULL,
	[Title] [nvarchar](50) NULL,
	[HireDate] [date] NULL,
	[BirthDate] [date] NULL,
	[LoginID] [nvarchar](256) NULL,
	[EmailAddress] [nvarchar](50) NULL,
	[Phone] [nvarchar](25) NULL,
	[MaritalStatus] [nchar](1) NULL,
	[EmergencyContactName] [nvarchar](50) NULL,
	[EmergencyContactPhone] [nvarchar](25) NULL,
	[SalariedFlag] [bit] NULL,
	[Gender] [nchar](1) NULL,
	[PayFrequency] [tinyint] NULL,
	[BaseRate] [money] NULL,
	[VacationHours] [smallint] NULL,
	[SickLeaveHours] [smallint] NULL,
	[CurrentFlag] [bit] NOT NULL,
	[SalesPersonFlag] [bit] NOT NULL,
	[DepartmentName] [nvarchar](50) NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[Status] [nvarchar](50) NULL,
	[EmployeePhoto] [varbinary](max) NULL,
 CONSTRAINT [PK_DimEmployee_EmployeeKey] PRIMARY KEY CLUSTERED 
(
	[EmployeeKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[DimOrganization]

In [0]:
/****** Object:  Table [dbo].[DimOrganization]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimOrganization](
	[OrganizationKey] [int] IDENTITY(1,1) NOT NULL,
	[ParentOrganizationKey] [int] NULL,
	[PercentageOfOwnership] [nvarchar](16) NULL,
	[OrganizationName] [nvarchar](50) NULL,
	[CurrencyKey] [int] NULL,
 CONSTRAINT [PK_DimOrganization] PRIMARY KEY CLUSTERED 
(
	[OrganizationKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimPromotion]

In [0]:
/****** Object:  Table [dbo].[DimPromotion]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimPromotion](
	[PromotionKey] [int] IDENTITY(1,1) NOT NULL,
	[PromotionAlternateKey] [int] NULL,
	[EnglishPromotionName] [nvarchar](255) NULL,
	[SpanishPromotionName] [nvarchar](255) NULL,
	[FrenchPromotionName] [nvarchar](255) NULL,
	[DiscountPct] [float] NULL,
	[EnglishPromotionType] [nvarchar](50) NULL,
	[SpanishPromotionType] [nvarchar](50) NULL,
	[FrenchPromotionType] [nvarchar](50) NULL,
	[EnglishPromotionCategory] [nvarchar](50) NULL,
	[SpanishPromotionCategory] [nvarchar](50) NULL,
	[FrenchPromotionCategory] [nvarchar](50) NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NULL,
	[MinQty] [int] NULL,
	[MaxQty] [int] NULL,
 CONSTRAINT [PK_DimPromotion_PromotionKey] PRIMARY KEY CLUSTERED 
(
	[PromotionKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_DimPromotion_PromotionAlternateKey] UNIQUE NONCLUSTERED 
(
	[PromotionAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimReseller]

In [0]:
/****** Object:  Table [dbo].[DimReseller]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimReseller](
	[ResellerKey] [int] IDENTITY(1,1) NOT NULL,
	[GeographyKey] [int] NULL,
	[ResellerAlternateKey] [nvarchar](15) NULL,
	[Phone] [nvarchar](25) NULL,
	[BusinessType] [varchar](20) NOT NULL,
	[ResellerName] [nvarchar](50) NOT NULL,
	[NumberEmployees] [int] NULL,
	[OrderFrequency] [char](1) NULL,
	[OrderMonth] [tinyint] NULL,
	[FirstOrderYear] [int] NULL,
	[LastOrderYear] [int] NULL,
	[ProductLine] [nvarchar](50) NULL,
	[AddressLine1] [nvarchar](60) NULL,
	[AddressLine2] [nvarchar](60) NULL,
	[AnnualSales] [money] NULL,
	[BankName] [nvarchar](50) NULL,
	[MinPaymentType] [tinyint] NULL,
	[MinPaymentAmount] [money] NULL,
	[AnnualRevenue] [money] NULL,
	[YearOpened] [int] NULL,
 CONSTRAINT [PK_DimReseller_ResellerKey] PRIMARY KEY CLUSTERED 
(
	[ResellerKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_DimReseller_ResellerAlternateKey] UNIQUE NONCLUSTERED 
(
	[ResellerAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimSalesReason]

In [0]:
/****** Object:  Table [dbo].[DimSalesReason]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimSalesReason](
	[SalesReasonKey] [int] IDENTITY(1,1) NOT NULL,
	[SalesReasonAlternateKey] [int] NOT NULL,
	[SalesReasonName] [nvarchar](50) NOT NULL,
	[SalesReasonReasonType] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DimSalesReason_SalesReasonKey] PRIMARY KEY CLUSTERED 
(
	[SalesReasonKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DimScenario]

In [0]:
/****** Object:  Table [dbo].[DimScenario]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimScenario](
	[ScenarioKey] [int] IDENTITY(1,1) NOT NULL,
	[ScenarioName] [nvarchar](50) NULL,
 CONSTRAINT [PK_DimScenario] PRIMARY KEY CLUSTERED 
(
	[ScenarioKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FactAdditionalInternationalProductDescription]

In [0]:
/****** Object:  Table [dbo].[FactAdditionalInternationalProductDescription]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactAdditionalInternationalProductDescription](
	[ProductKey] [int] NOT NULL,
	[CultureName] [nvarchar](50) NOT NULL,
	[ProductDescription] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_FactAdditionalInternationalProductDescription_ProductKey_CultureName] PRIMARY KEY CLUSTERED 
(
	[ProductKey] ASC,
	[CultureName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[FactCallCenter]

In [0]:
/****** Object:  Table [dbo].[FactCallCenter]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactCallCenter](
	[FactCallCenterID] [int] IDENTITY(1,1) NOT NULL,
	[DateKey] [int] NOT NULL,
	[WageType] [nvarchar](15) NOT NULL,
	[Shift] [nvarchar](20) NOT NULL,
	[LevelOneOperators] [smallint] NOT NULL,
	[LevelTwoOperators] [smallint] NOT NULL,
	[TotalOperators] [smallint] NOT NULL,
	[Calls] [int] NOT NULL,
	[AutomaticResponses] [int] NOT NULL,
	[Orders] [int] NOT NULL,
	[IssuesRaised] [smallint] NOT NULL,
	[AverageTimePerIssue] [smallint] NOT NULL,
	[ServiceGrade] [float] NOT NULL,
	[Date] [datetime] NULL,
 CONSTRAINT [PK_FactCallCenter_FactCallCenterID] PRIMARY KEY CLUSTERED 
(
	[FactCallCenterID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_FactCallCenter_DateKey_Shift] UNIQUE NONCLUSTERED 
(
	[DateKey] ASC,
	[Shift] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FactCurrencyRate]

In [0]:
/****** Object:  Table [dbo].[FactCurrencyRate]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactCurrencyRate](
	[CurrencyKey] [int] NOT NULL,
	[DateKey] [int] NOT NULL,
	[AverageRate] [float] NOT NULL,
	[EndOfDayRate] [float] NOT NULL,
	[Date] [datetime] NULL,
 CONSTRAINT [PK_FactCurrencyRate_CurrencyKey_DateKey] PRIMARY KEY CLUSTERED 
(
	[CurrencyKey] ASC,
	[DateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FactFinance]

In [0]:
/****** Object:  Table [dbo].[FactFinance]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactFinance](
	[FinanceKey] [int] IDENTITY(1,1) NOT NULL,
	[DateKey] [int] NOT NULL,
	[OrganizationKey] [int] NOT NULL,
	[DepartmentGroupKey] [int] NOT NULL,
	[ScenarioKey] [int] NOT NULL,
	[AccountKey] [int] NOT NULL,
	[Amount] [float] NOT NULL,
	[Date] [datetime] NULL
) ON [PRIMARY]
GO

# [dbo].[FactInternetSalesReason]

In [0]:
/****** Object:  Table [dbo].[FactInternetSalesReason]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactInternetSalesReason](
	[SalesOrderNumber] [nvarchar](20) NOT NULL,
	[SalesOrderLineNumber] [tinyint] NOT NULL,
	[SalesReasonKey] [int] NOT NULL,
 CONSTRAINT [PK_FactInternetSalesReason_SalesOrderNumber_SalesOrderLineNumber_SalesReasonKey] PRIMARY KEY CLUSTERED 
(
	[SalesOrderNumber] ASC,
	[SalesOrderLineNumber] ASC,
	[SalesReasonKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FactProductInventory]

In [0]:
/****** Object:  Table [dbo].[FactProductInventory]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactProductInventory](
	[ProductKey] [int] NOT NULL,
	[DateKey] [int] NOT NULL,
	[MovementDate] [date] NOT NULL,
	[UnitCost] [money] NOT NULL,
	[UnitsIn] [int] NOT NULL,
	[UnitsOut] [int] NOT NULL,
	[UnitsBalance] [int] NOT NULL,
 CONSTRAINT [PK_FactProductInventory] PRIMARY KEY CLUSTERED 
(
	[ProductKey] ASC,
	[DateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FactResellerExpand]

In [0]:
/****** Object:  Table [dbo].[FactResellerExpand]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactResellerExpand](
	[ProductKey] [int] NOT NULL,
	[OrderDateKey] [int] NOT NULL,
	[DueDateKey] [int] NOT NULL,
	[ShipDateKey] [int] NOT NULL,
	[ResellerKey] [int] NOT NULL,
	[EmployeeKey] [int] NOT NULL,
	[PromotionKey] [int] NOT NULL,
	[CurrencyKey] [int] NOT NULL,
	[SalesTerritoryKey] [int] NOT NULL,
	[SalesOrderNumber] [nvarchar](20) NOT NULL,
	[SalesOrderLineNumber] [tinyint] NOT NULL,
	[RevisionNumber] [tinyint] NULL,
	[OrderQuantity] [smallint] NULL,
	[UnitPrice] [money] NULL,
	[ExtendedAmount] [money] NULL,
	[UnitPriceDiscountPct] [float] NULL,
	[DiscountAmount] [float] NULL,
	[ProductStandardCost] [money] NULL,
	[TotalProductCost] [money] NULL,
	[SalesAmount] [money] NULL,
	[TaxAmt] [money] NULL,
	[Freight] [money] NULL,
	[CarrierTrackingNumber] [nvarchar](25) NULL,
	[CustomerPONumber] [nvarchar](25) NULL,
	[OrderDate] [datetime] NULL,
	[DueDate] [datetime] NULL,
	[ShipDate] [datetime] NULL,
	[CurrencyKey2] [int] NOT NULL,
	[DateKey] [int] NOT NULL,
	[EmployeeKey2] [int] NOT NULL
) ON [PRIMARY]
GO

# [dbo].[FactResellerSales]

In [0]:
/****** Object:  Table [dbo].[FactResellerSales]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactResellerSales](
	[ProductKey] [int] NOT NULL,
	[OrderDateKey] [int] NOT NULL,
	[DueDateKey] [int] NOT NULL,
	[ShipDateKey] [int] NOT NULL,
	[ResellerKey] [int] NOT NULL,
	[EmployeeKey] [int] NOT NULL,
	[PromotionKey] [int] NOT NULL,
	[CurrencyKey] [int] NOT NULL,
	[SalesTerritoryKey] [int] NOT NULL,
	[SalesOrderNumber] [nvarchar](20) NOT NULL,
	[SalesOrderLineNumber] [tinyint] NOT NULL,
	[RevisionNumber] [tinyint] NULL,
	[OrderQuantity] [smallint] NULL,
	[UnitPrice] [money] NULL,
	[ExtendedAmount] [money] NULL,
	[UnitPriceDiscountPct] [float] NULL,
	[DiscountAmount] [float] NULL,
	[ProductStandardCost] [money] NULL,
	[TotalProductCost] [money] NULL,
	[SalesAmount] [money] NULL,
	[TaxAmt] [money] NULL,
	[Freight] [money] NULL,
	[CarrierTrackingNumber] [nvarchar](25) NULL,
	[CustomerPONumber] [nvarchar](25) NULL,
	[OrderDate] [datetime] NULL,
	[DueDate] [datetime] NULL,
	[ShipDate] [datetime] NULL,
 CONSTRAINT [PK_FactResellerSales_SalesOrderNumber_SalesOrderLineNumber] PRIMARY KEY CLUSTERED 
(
	[SalesOrderNumber] ASC,
	[SalesOrderLineNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FactSalesQuota]

In [0]:
/****** Object:  Table [dbo].[FactSalesQuota]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactSalesQuota](
	[SalesQuotaKey] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeKey] [int] NOT NULL,
	[DateKey] [int] NOT NULL,
	[CalendarYear] [smallint] NOT NULL,
	[CalendarQuarter] [tinyint] NOT NULL,
	[SalesAmountQuota] [money] NOT NULL,
	[Date] [datetime] NULL,
 CONSTRAINT [PK_FactSalesQuota_SalesQuotaKey] PRIMARY KEY CLUSTERED 
(
	[SalesQuotaKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FactSurveyResponse]

In [0]:
/****** Object:  Table [dbo].[FactSurveyResponse]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactSurveyResponse](
	[SurveyResponseKey] [int] IDENTITY(1,1) NOT NULL,
	[DateKey] [int] NOT NULL,
	[CustomerKey] [int] NOT NULL,
	[ProductCategoryKey] [int] NOT NULL,
	[EnglishProductCategoryName] [nvarchar](50) NOT NULL,
	[ProductSubcategoryKey] [int] NOT NULL,
	[EnglishProductSubcategoryName] [nvarchar](50) NOT NULL,
	[Date] [datetime] NULL,
 CONSTRAINT [PK_FactSurveyResponse_SurveyResponseKey] PRIMARY KEY CLUSTERED 
(
	[SurveyResponseKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FrequentlyUsedJobs]

In [0]:
/****** Object:  Table [dbo].[FrequentlyUsedJobs]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FrequentlyUsedJobs](
	[name] [sysname] NOT NULL,
	[total_jobs_executed] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[FrequentlyUsedQueries]

In [0]:
/****** Object:  Table [dbo].[FrequentlyUsedQueries]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FrequentlyUsedQueries](
	[creation_date] [date] NULL,
	[last_execution_Date] [date] NULL,
	[execution_count] [bigint] NOT NULL,
	[total_used_grant_kb] [bigint] NULL,
	[total_elapsed_time] [bigint] NOT NULL,
	[total_grant_kb] [bigint] NULL,
	[total_physical_reads] [bigint] NOT NULL,
	[last_physical_reads] [bigint] NOT NULL,
	[max_physical_reads] [bigint] NOT NULL,
	[total_logical_writes] [bigint] NOT NULL,
	[total_logical_reads] [bigint] NOT NULL,
	[total_rows] [bigint] NULL,
	[query_text] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[function_info]

In [0]:
/****** Object:  Table [dbo].[function_info]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[function_info](
	[database_name] [nvarchar](100) NULL,
	[schema_name] [varchar](100) NULL,
	[function_name] [varchar](100) NULL,
	[function_type] [varchar](100) NULL,
	[parameter] [varchar](max) NULL,
	[parameter_datatype] [varchar](max) NULL,
	[return_type] [varchar](100) NULL,
	[length_of_code] [bigint] NULL,
	[last_modified_datetime] [datetime] NULL,
	[last_execution_time] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[function_info_test]

In [0]:
/****** Object:  Table [dbo].[function_info_test]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[function_info_test](
	[database_name] [nvarchar](100) NULL,
	[schema_name] [varchar](100) NULL,
	[function_name] [varchar](100) NULL,
	[function_type] [varchar](100) NULL,
	[parameter] [varchar](max) NULL,
	[parameter_datatype] [varchar](max) NULL,
	[return_type] [varchar](100) NULL,
	[length_of_code] [bigint] NULL,
	[last_modified_datetime] [datetime] NULL,
	[last_execution_time] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[JobDetails]

In [0]:
/****** Object:  Table [dbo].[JobDetails]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JobDetails](
	[database_name] [sysname] NULL,
	[job_name] [sysname] NOT NULL,
	[enabled] [varchar](3) NOT NULL,
	[last_modified_datetime] [datetime] NOT NULL,
	[last_run_outcome] [varchar](9) NULL,
	[originating_server_id] [int] NOT NULL,
	[description] [nvarchar](512) NULL,
	[step_id] [int] NULL,
	[step_name] [sysname] NULL,
	[length_of_code] [bigint] NULL,
	[command] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[keywordfile]

In [0]:
/****** Object:  Table [dbo].[keywordfile]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[keywordfile](
	[Column 0] [varchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[keywordfile1]

In [0]:
/****** Object:  Table [dbo].[keywordfile1]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[keywordfile1](
	[column1] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO

# [dbo].[Keywords]

In [0]:
/****** Object:  Table [dbo].[Keywords]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Keywords](
	[Keyword] [varchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[LinkedServer_Details]

In [0]:
/****** Object:  Table [dbo].[LinkedServer_Details]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LinkedServer_Details](
	[name] [sysname] NOT NULL,
	[product] [sysname] NOT NULL,
	[provider] [sysname] NOT NULL,
	[data_source] [nvarchar](4000) NULL,
	[is_linked] [bit] NOT NULL
) ON [PRIMARY]
GO

# [dbo].[MaxColumns]

In [0]:
/****** Object:  Table [dbo].[MaxColumns]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MaxColumns](
	[DatabaseName] [nvarchar](max) NULL,
	[Tablename] [nvarchar](max) NULL,
	[ColumnCount] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[MemoryUtilByJobs]

In [0]:
/****** Object:  Table [dbo].[MemoryUtilByJobs]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MemoryUtilByJobs](
	[JobName] [sysname] NOT NULL,
	[LoginTime] [datetime] NULL,
	[SessionId] [smallint] NULL,
	[ElapsedTime] [int] NULL,
	[MemoryUsage] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[MemoryUtilByQuery]

In [0]:
/****** Object:  Table [dbo].[MemoryUtilByQuery]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MemoryUtilByQuery](
	[database_name] [nvarchar](128) NULL,
	[creation_date] [date] NULL,
	[last_execution_date] [date] NULL,
	[execution_count] [bigint] NOT NULL,
	[total_used_grant_kb] [bigint] NULL,
	[total_elapsed_time] [bigint] NOT NULL,
	[total_grant_kb] [bigint] NULL,
	[total_physical_reads] [bigint] NOT NULL,
	[last_physical_reads] [bigint] NOT NULL,
	[max_physical_reads] [bigint] NOT NULL,
	[total_logical_writes] [bigint] NOT NULL,
	[total_logical_reads] [bigint] NOT NULL,
	[total_rows] [bigint] NULL,
	[query_runtime] [bigint] NULL,
	[query_text] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[NewFactCurrencyRate]

In [0]:
/****** Object:  Table [dbo].[NewFactCurrencyRate]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NewFactCurrencyRate](
	[AverageRate] [real] NULL,
	[CurrencyID] [nvarchar](3) NULL,
	[CurrencyDate] [date] NULL,
	[EndOfDayRate] [real] NULL,
	[CurrencyKey] [int] NULL,
	[DateKey] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[partition_cluster_recommendation]

In [0]:
/****** Object:  Table [dbo].[partition_cluster_recommendation]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[partition_cluster_recommendation](
	[database_name] [varchar](100) NOT NULL,
	[schema_name] [nvarchar](128) NULL,
	[table_name] [sysname] NOT NULL,
	[index_name] [sysname] NULL,
	[type_desc] [nvarchar](200) NULL,
	[Index_size_KB] [bigint] NULL,
	[column_name] [sysname] NULL,
	[is_primary_key] [varchar](3) NOT NULL,
	[is_unique_constraint] [varchar](3) NOT NULL,
	[is_index_disabled] [varchar](3) NOT NULL,
	[max_column_id_used] [int] NOT NULL,
	[max_column_used] [sysname] NULL,
	[datatype] [sysname] NULL,
	[user_seeks] [bigint] NULL,
	[user_scans] [bigint] NULL,
	[user_lookups] [bigint] NULL,
	[user_updates] [bigint] NULL,
	[partition_number] [int] NULL,
	[rows] [bigint] NULL,
	[data_compression_desc] [nvarchar](60) NULL,
	[partition_id] [bigint] NULL,
	[filegroup_name] [sysname] NULL
) ON [PRIMARY]
GO

# [dbo].[partition_recom_test]

In [0]:
/****** Object:  Table [dbo].[partition_recom_test]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[partition_recom_test](
	[database_name] [varchar](100) NOT NULL,
	[schema_name] [nvarchar](128) NULL,
	[table_name] [sysname] NOT NULL,
	[index_name] [sysname] NULL,
	[type_desc] [nvarchar](200) NULL,
	[Index_size_KB] [bigint] NULL,
	[column_name] [sysname] NULL,
	[is_primary_key] [varchar](3) NOT NULL,
	[is_unique_constraint] [varchar](3) NOT NULL,
	[is_index_disabled] [varchar](3) NOT NULL,
	[max_column_id_used] [int] NOT NULL,
	[max_column_used] [sysname] NULL,
	[datatype] [sysname] NULL,
	[user_seeks] [bigint] NULL,
	[user_scans] [bigint] NULL,
	[user_lookups] [bigint] NULL,
	[user_updates] [bigint] NULL,
	[partition_number] [int] NULL,
	[rows] [bigint] NULL,
	[data_compression_desc] [nvarchar](60) NULL,
	[partition_id] [bigint] NULL,
	[filegroup_name] [sysname] NULL
) ON [PRIMARY]
GO

# [dbo].[procedure_info]

In [0]:
/****** Object:  Table [dbo].[procedure_info]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[procedure_info](
	[database_name] [varchar](100) NULL,
	[schema_name] [varchar](100) NULL,
	[object_name] [varchar](100) NULL,
	[parameter_name] [varchar](100) NULL,
	[parameter_datatype] [varchar](100) NULL,
	[parameter_max_bytes] [int] NULL,
	[output_parameter] [varchar](100) NULL,
	[length_of_code] [int] NULL,
	[last_modified_datetime] [datetime] NULL,
	[last_execution_time] [datetime] NULL
) ON [PRIMARY]
GO

# [dbo].[ProspectiveBuyer]

In [0]:
/****** Object:  Table [dbo].[ProspectiveBuyer]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProspectiveBuyer](
	[ProspectiveBuyerKey] [int] IDENTITY(1,1) NOT NULL,
	[ProspectAlternateKey] [nvarchar](15) NULL,
	[FirstName] [nvarchar](50) NULL,
	[MiddleName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[BirthDate] [datetime] NULL,
	[MaritalStatus] [nchar](1) NULL,
	[Gender] [nvarchar](1) NULL,
	[EmailAddress] [nvarchar](50) NULL,
	[YearlyIncome] [money] NULL,
	[TotalChildren] [tinyint] NULL,
	[NumberChildrenAtHome] [tinyint] NULL,
	[Education] [nvarchar](40) NULL,
	[Occupation] [nvarchar](100) NULL,
	[HouseOwnerFlag] [nchar](1) NULL,
	[NumberCarsOwned] [tinyint] NULL,
	[AddressLine1] [nvarchar](120) NULL,
	[AddressLine2] [nvarchar](120) NULL,
	[City] [nvarchar](30) NULL,
	[StateProvinceCode] [nvarchar](3) NULL,
	[PostalCode] [nvarchar](15) NULL,
	[Phone] [nvarchar](20) NULL,
	[Salutation] [nvarchar](8) NULL,
	[Unknown] [int] NULL,
 CONSTRAINT [PK_ProspectiveBuyer_ProspectiveBuyerKey] PRIMARY KEY CLUSTERED 
(
	[ProspectiveBuyerKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[query_cost_test]

In [0]:
/****** Object:  Table [dbo].[query_cost_test]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[query_cost_test](
	[ProductKey] [int] NOT NULL,
	[OrderDateKey] [int] NOT NULL,
	[DueDateKey] [int] NOT NULL,
	[ShipDateKey] [int] NOT NULL,
	[ResellerKey] [int] NOT NULL,
	[EmployeeKey] [int] NOT NULL,
	[PromotionKey] [int] NOT NULL,
	[CurrencyKey] [int] NOT NULL,
	[SalesTerritoryKey] [int] NOT NULL,
	[SalesOrderNumber] [nvarchar](20) NOT NULL,
	[SalesOrderLineNumber] [tinyint] NOT NULL,
	[RevisionNumber] [tinyint] NULL,
	[OrderQuantity] [smallint] NULL,
	[UnitPrice] [money] NULL,
	[ExtendedAmount] [money] NULL,
	[UnitPriceDiscountPct] [float] NULL,
	[DiscountAmount] [float] NULL,
	[ProductStandardCost] [money] NULL,
	[TotalProductCost] [money] NULL,
	[SalesAmount] [money] NULL,
	[TaxAmt] [money] NULL,
	[Freight] [money] NULL,
	[CarrierTrackingNumber] [nvarchar](25) NULL,
	[CustomerPONumber] [nvarchar](25) NULL,
	[OrderDate] [datetime] NULL,
	[DueDate] [datetime] NULL,
	[ShipDate] [datetime] NULL
) ON [PRIMARY]
GO

# [dbo].[query_data]

In [0]:
/****** Object:  Table [dbo].[query_data]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[query_data](
	[query] [varchar](1000) NULL,
	[execution_date] [datetime] NULL,
	[databasename] [varchar](500) NULL
) ON [PRIMARY]
GO

# [dbo].[query_stats]

In [0]:
/****** Object:  Table [dbo].[query_stats]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[query_stats](
	[query_frequency] [int] NULL,
	[average_data_returned_by_query_in_gb] [float] NULL,
	[size_of_data_files_in_gb] [float] NULL,
	[size_of_log_files_in_gb] [float] NULL,
	[total_data_transferred_in_gb] [decimal](18, 9) NULL,
	[total_log_transferred_in_gb] [decimal](18, 9) NULL,
	[total_cost] [decimal](18, 9) NULL
) ON [PRIMARY]
GO

# [dbo].[query_storage_cost_per_month]

In [0]:
/****** Object:  Table [dbo].[query_storage_cost_per_month]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[query_storage_cost_per_month](
	[database_name] [varchar](500) NULL,
	[Cost_per_month] [decimal](18, 9) NULL
) ON [PRIMARY]
GO

# [dbo].[report_data]

In [0]:
/****** Object:  Table [dbo].[report_data]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[report_data](
	[Description] [varchar](500) NULL,
	[Count] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[research_cost]

In [0]:
/****** Object:  Table [dbo].[research_cost]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[research_cost](
	[description] [decimal](18, 9) NULL
) ON [PRIMARY]
GO

# [dbo].[research_cost1]

In [0]:
/****** Object:  Table [dbo].[research_cost1]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[research_cost1](
	[column1] [decimal](18, 9) NULL,
	[column2] [decimal](18, 9) NULL,
	[column3] [decimal](18, 9) NULL,
	[column4] [decimal](18, 9) NULL
) ON [PRIMARY]
GO

# [dbo].[research_cost2]

In [0]:
/****** Object:  Table [dbo].[research_cost2]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[research_cost2](
	[query_freq] [decimal](18, 9) NULL,
	[data_returned] [decimal](18, 9) NULL,
	[execution_time] [decimal](18, 9) NULL,
	[size_of_data] [decimal](18, 9) NULL
) ON [PRIMARY]
GO

# [dbo].[research_cost3]

In [0]:
/****** Object:  Table [dbo].[research_cost3]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[research_cost3](
	[query_frequency] [int] NULL,
	[average_data_returned_by_query_in_gb] [float] NULL,
	[size_of_data_files_in_gb] [float] NULL,
	[size_of_log_files_in_gb] [float] NULL
) ON [PRIMARY]
GO

# [dbo].[research_cost4]

In [0]:
/****** Object:  Table [dbo].[research_cost4]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[research_cost4](
	[query_frequency] [int] NULL,
	[average_data_returned_by_query_in_gb] [float] NULL,
	[size_of_data_files_in_gb] [float] NULL,
	[size_of_log_files_in_gb] [float] NULL,
	[total_data_transferred_in_gb] [float] NULL,
	[total_log_transferred_in_gb] [float] NULL
) ON [PRIMARY]
GO

# [dbo].[sample_cost]

In [0]:
/****** Object:  Table [dbo].[sample_cost]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sample_cost](
	[query_frequency] [int] NULL,
	[average_data_returned_by_query_in_gb] [float] NULL,
	[size_of_data_files_in_gb] [float] NULL,
	[size_of_log_files_in_gb] [float] NULL
) ON [PRIMARY]
GO

# [dbo].[sample_cost1]

In [0]:
/****** Object:  Table [dbo].[sample_cost1]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sample_cost1](
	[query_frequency] [int] NULL,
	[average_data_returned_by_query_in_gb] [float] NULL,
	[size_of_data_files_in_gb] [float] NULL,
	[size_of_log_files_in_gb] [float] NULL,
	[total_data_transferred_in_gb] [float] NULL,
	[total_log_transferred_in_gb] [float] NULL,
	[total_query_usage_in_gb] [float] NULL,
	[total_cost] [float] NULL
) ON [PRIMARY]
GO

# [dbo].[SlowestJobs]

In [0]:
/****** Object:  Table [dbo].[SlowestJobs]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SlowestJobs](
	[JobName] [sysname] NOT NULL,
	[StepName] [sysname] NOT NULL,
	[DurationInSeconds] [int] NOT NULL,
	[RunDate] [datetime] NULL,
	[RunTime] [datetime] NULL,
	[LastMessage] [nvarchar](4000) NULL
) ON [PRIMARY]
GO

# [dbo].[SlowestQueries]

In [0]:
/****** Object:  Table [dbo].[SlowestQueries]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SlowestQueries](
	[creation_date] [date] NULL,
	[last_execution_date] [date] NULL,
	[total_physical_reads] [bigint] NOT NULL,
	[total_logical_reads] [bigint] NOT NULL,
	[total_logical_writes] [bigint] NOT NULL,
	[execution_count] [bigint] NOT NULL,
	[total_worker_time] [bigint] NOT NULL,
	[total_used_grant_kb] [bigint] NULL,
	[total_elapsed_time] [bigint] NOT NULL,
	[query_run_time] [bigint] NULL
) ON [PRIMARY]
GO

# [dbo].[SqlText]

In [0]:
/****** Object:  Table [dbo].[SqlText]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SqlText](
	[sql_handle] [varbinary](64) NOT NULL,
	[text] [nvarchar](max) NULL,
 CONSTRAINT [AK_SqlText_sql_handle] UNIQUE NONCLUSTERED 
(
	[sql_handle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[synonym_info]

In [0]:
/****** Object:  Table [dbo].[synonym_info]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[synonym_info](
	[database_name] [varchar](100) NULL,
	[schema_name] [varchar](100) NULL,
	[synonym_name] [varchar](100) NULL,
	[type] [varchar](20) NULL,
	[last_modified_date] [datetime] NULL,
	[base_object_name] [varchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[Table_Details]

In [0]:
/****** Object:  Table [dbo].[Table_Details]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_Details](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[DataBaseName] [nvarchar](100) NULL,
	[TableName] [nvarchar](1000) NULL,
	[TypeDesc] [char](20) NULL,
	[TableType] [nvarchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[table_info]

In [0]:
/****** Object:  Table [dbo].[table_info]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[table_info](
	[database_name] [varchar](50) NULL,
	[schema_name] [varchar](50) NULL,
	[table_name] [varchar](300) NULL,
	[type] [varchar](200) NULL,
	[number_columns] [int] NULL,
	[rows] [int] NULL,
	[size] [numeric](18, 3) NULL
) ON [PRIMARY]
GO

# [dbo].[Table_SizeDetails]

In [0]:
/****** Object:  Table [dbo].[Table_SizeDetails]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_SizeDetails](
	[DBNAME] [varchar](max) NULL,
	[TABLE_Name] [varchar](max) NULL,
	[table_schema] [varchar](max) NULL,
	[row_count] [int] NULL,
	[TABLE_Size_in_kb] [numeric](10, 2) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Test_Dvt]

In [0]:
/****** Object:  Table [dbo].[Test_Dvt]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Test_Dvt](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](10) NULL,
	[company] [nchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[trigger_info]

In [0]:
/****** Object:  Table [dbo].[trigger_info]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[trigger_info](
	[database_name] [varchar](50) NULL,
	[schema_name] [varchar](50) NULL,
	[trigger_name] [varchar](200) NULL,
	[trigger_owner] [varchar](200) NULL,
	[table_name] [varchar](200) NULL,
	[is_update] [varchar](3) NULL,
	[is_delete] [varchar](3) NULL,
	[is_insert] [varchar](3) NULL,
	[is_after] [varchar](3) NULL,
	[is_instead_of] [varchar](3) NULL,
	[disabled] [varchar](3) NULL
) ON [PRIMARY]
GO

# [dbo].[UnusedObjectDetails]

In [0]:
/****** Object:  Table [dbo].[UnusedObjectDetails]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UnusedObjectDetails](
	[DatabaseName] [nvarchar](max) NULL,
	[ObjectName] [nvarchar](max) NULL,
	[SchemaName] [nvarchar](max) NULL,
	[RowCount] [int] NULL,
	[CreatedDate] [datetime] NULL,
	[LastModifiedDate] [datetime] NULL,
	[ColumnCount] [int] NULL,
	[TypeDesc] [nvarchar](20) NULL,
	[ParameterDataType] [nvarchar](20) NULL,
	[ParameterName] [nvarchar](20) NULL,
	[OutputParameter] [nvarchar](20) NULL,
	[LengthOfCode] [int] NULL,
	[LastExecutionDate] [datetime] NULL,
	[is_update] [varchar](5) NULL,
	[is_delete] [varchar](5) NULL,
	[is_insert] [varchar](5) NULL,
	[is_after] [varchar](5) NULL,
	[is_instead_of] [varchar](5) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[unusedobjects]

In [0]:
/****** Object:  Table [dbo].[unusedobjects]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[unusedobjects](
	[object_name] [varchar](250) NULL,
	[database_name] [varchar](250) NULL,
	[schema_name] [varchar](250) NULL,
	[object_type] [varchar](250) NULL,
	[last_modified_date] [datetime] NULL,
	[last_execution_time] [datetime] NULL,
	[lenght_of_code] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[unusedobjects_Details]

In [0]:
/****** Object:  Table [dbo].[unusedobjects_Details]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[unusedobjects_Details](
	[object_name] [varchar](100) NULL,
	[database_name] [varchar](100) NULL,
	[schema_name] [varchar](100) NULL,
	[object_type] [varchar](100) NULL,
	[last_modified_datetime] [datetime] NULL,
	[last_execution_time] [datetime] NULL,
	[length_of_code] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[unusedobjects_Details_test1]

In [0]:
/****** Object:  Table [dbo].[unusedobjects_Details_test1]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[unusedobjects_Details_test1](
	[object_name] [varchar](100) NULL,
	[database_name] [varchar](100) NULL,
	[schema_name] [varchar](100) NULL,
	[object_type] [varchar](100) NULL,
	[last_execution_time] [datetime] NULL,
	[length_of_code] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[UnusedTableDetails]

In [0]:
/****** Object:  Table [dbo].[UnusedTableDetails]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UnusedTableDetails](
	[DatabaseName] [nvarchar](128) NULL,
	[Table_Name] [sysname] NOT NULL,
	[Row_Count] [bigint] NULL,
	[SchemaName] [sysname] NULL,
	[Created_Date] [datetime] NOT NULL,
	[Last_Modified_Date] [datetime] NOT NULL,
	[type_desc] [nvarchar](60) NULL,
	[Column_Count] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[User_defined_data_tye_info]

In [0]:
/****** Object:  Table [dbo].[User_defined_data_tye_info]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_defined_data_tye_info](
	[database_name] [varchar](50) NULL,
	[schema_name] [varchar](50) NULL,
	[data_type_name] [varchar](100) NULL,
	[actual_datatype] [varchar](100) NULL,
	[max_length] [bigint] NULL,
	[precision] [numeric](18, 3) NULL,
	[Is_nullable] [varchar](3) NULL
) ON [PRIMARY]
GO

# [dbo].[UserDetails]

In [0]:
/****** Object:  Table [dbo].[UserDetails]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserDetails](
	[SPID] [int] NULL,
	[Status] [varchar](50) NULL,
	[Login] [varchar](100) NULL,
	[Hostname] [varchar](100) NULL,
	[dbname] [varchar](50) NULL,
	[LastBatch] [varchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[UserPermissionDetails]

In [0]:
/****** Object:  Table [dbo].[UserPermissionDetails]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserPermissionDetails](
	[DatabaseName] [sysname] NOT NULL,
	[UserName] [sysname] NOT NULL,
	[TypeDesc] [nvarchar](60) NULL,
	[RoleName] [varchar](255) NULL,
	[LastLogin] [datetime] NULL,
	[PermissionName] [varchar](256) NULL
) ON [PRIMARY]
GO

# [dbo].[UsersDetails]

In [0]:
/****** Object:  Table [dbo].[UsersDetails]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsersDetails](
	[name] [sysname] NOT NULL,
	[type_desc] [nvarchar](60) NULL,
	[is_disabled] [bit] NULL
) ON [PRIMARY]
GO

# [dbo].[view_info]

In [0]:
/****** Object:  Table [dbo].[view_info]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[view_info](
	[database_name] [varchar](100) NULL,
	[schema_name] [varchar](100) NULL,
	[table_name] [varchar](300) NULL,
	[type] [varchar](200) NULL,
	[number_columns] [int] NULL
) ON [PRIMARY]
GO

# [AK_DimCurrency_CurrencyAlternateKey]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [AK_DimCurrency_CurrencyAlternateKey]    Script Date: 25-05-2023 18:33:54 ******/
CREATE UNIQUE NONCLUSTERED INDEX [AK_DimCurrency_CurrencyAlternateKey] ON [dbo].[DimCurrency]
(
	[CurrencyAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

# [IX_DimCustomer_CustomerAlternateKey]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_DimCustomer_CustomerAlternateKey]    Script Date: 25-05-2023 18:33:54 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_DimCustomer_CustomerAlternateKey] ON [dbo].[DimCustomer]
(
	[CustomerAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

# [AK_DimDate_FullDateAlternateKey]

In [0]:
/****** Object:  Index [AK_DimDate_FullDateAlternateKey]    Script Date: 25-05-2023 18:33:54 ******/
CREATE UNIQUE NONCLUSTERED INDEX [AK_DimDate_FullDateAlternateKey] ON [dbo].[DimDate]
(
	[FullDateAlternateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

# [FK_DimAccount_DimAccount]

In [0]:
ALTER TABLE [dbo].[DimAccount]  WITH CHECK ADD  CONSTRAINT [FK_DimAccount_DimAccount] FOREIGN KEY([ParentAccountKey])
REFERENCES [dbo].[DimAccount] ([AccountKey])
GO
ALTER TABLE [dbo].[DimAccount] CHECK CONSTRAINT [FK_DimAccount_DimAccount]
GO

# [FK_DimCustomer_DimGeography]

In [0]:
ALTER TABLE [dbo].[DimCustomer]  WITH CHECK ADD  CONSTRAINT [FK_DimCustomer_DimGeography] FOREIGN KEY([GeographyKey])
REFERENCES [dbo].[DimGeography] ([GeographyKey])
GO
ALTER TABLE [dbo].[DimCustomer] CHECK CONSTRAINT [FK_DimCustomer_DimGeography]
GO

# [FK_DimDepartmentGroup_DimDepartmentGroup]

In [0]:
ALTER TABLE [dbo].[DimDepartmentGroup]  WITH CHECK ADD  CONSTRAINT [FK_DimDepartmentGroup_DimDepartmentGroup] FOREIGN KEY([ParentDepartmentGroupKey])
REFERENCES [dbo].[DimDepartmentGroup] ([DepartmentGroupKey])
GO
ALTER TABLE [dbo].[DimDepartmentGroup] CHECK CONSTRAINT [FK_DimDepartmentGroup_DimDepartmentGroup]
GO

# [FK_DimEmployee_DimEmployee]

In [0]:
ALTER TABLE [dbo].[DimEmployee]  WITH CHECK ADD  CONSTRAINT [FK_DimEmployee_DimEmployee] FOREIGN KEY([ParentEmployeeKey])
REFERENCES [dbo].[DimEmployee] ([EmployeeKey])
GO
ALTER TABLE [dbo].[DimEmployee] CHECK CONSTRAINT [FK_DimEmployee_DimEmployee]
GO

# [FK_DimEmployee_DimSalesTerritory]

In [0]:
ALTER TABLE [dbo].[DimEmployee]  WITH CHECK ADD  CONSTRAINT [FK_DimEmployee_DimSalesTerritory] FOREIGN KEY([SalesTerritoryKey])
REFERENCES [dbo].[DimSalesTerritory] ([SalesTerritoryKey])
GO
ALTER TABLE [dbo].[DimEmployee] CHECK CONSTRAINT [FK_DimEmployee_DimSalesTerritory]
GO

# [FK_DimGeography_DimSalesTerritory]

In [0]:
ALTER TABLE [dbo].[DimGeography]  WITH CHECK ADD  CONSTRAINT [FK_DimGeography_DimSalesTerritory] FOREIGN KEY([SalesTerritoryKey])
REFERENCES [dbo].[DimSalesTerritory] ([SalesTerritoryKey])
GO
ALTER TABLE [dbo].[DimGeography] CHECK CONSTRAINT [FK_DimGeography_DimSalesTerritory]
GO

# [FK_DimOrganization_DimCurrency]

In [0]:
ALTER TABLE [dbo].[DimOrganization]  WITH CHECK ADD  CONSTRAINT [FK_DimOrganization_DimCurrency] FOREIGN KEY([CurrencyKey])
REFERENCES [dbo].[DimCurrency] ([CurrencyKey])
GO
ALTER TABLE [dbo].[DimOrganization] CHECK CONSTRAINT [FK_DimOrganization_DimCurrency]
GO

# [FK_DimOrganization_DimOrganization]

In [0]:
ALTER TABLE [dbo].[DimOrganization]  WITH CHECK ADD  CONSTRAINT [FK_DimOrganization_DimOrganization] FOREIGN KEY([ParentOrganizationKey])
REFERENCES [dbo].[DimOrganization] ([OrganizationKey])
GO
ALTER TABLE [dbo].[DimOrganization] CHECK CONSTRAINT [FK_DimOrganization_DimOrganization]
GO

# [FK_DimProduct_DimProductSubcategory]

In [0]:
ALTER TABLE [dbo].[DimProduct]  WITH CHECK ADD  CONSTRAINT [FK_DimProduct_DimProductSubcategory] FOREIGN KEY([ProductSubcategoryKey])
REFERENCES [dbo].[DimProductSubcategory] ([ProductSubcategoryKey])
GO
ALTER TABLE [dbo].[DimProduct] CHECK CONSTRAINT [FK_DimProduct_DimProductSubcategory]
GO

# [FK_DimProductSubcategory_DimProductCategory]

In [0]:
ALTER TABLE [dbo].[DimProductSubcategory]  WITH CHECK ADD  CONSTRAINT [FK_DimProductSubcategory_DimProductCategory] FOREIGN KEY([ProductCategoryKey])
REFERENCES [dbo].[DimProductCategory] ([ProductCategoryKey])
GO
ALTER TABLE [dbo].[DimProductSubcategory] CHECK CONSTRAINT [FK_DimProductSubcategory_DimProductCategory]
GO

# [FK_DimReseller_DimGeography]

In [0]:
ALTER TABLE [dbo].[DimReseller]  WITH CHECK ADD  CONSTRAINT [FK_DimReseller_DimGeography] FOREIGN KEY([GeographyKey])
REFERENCES [dbo].[DimGeography] ([GeographyKey])
GO
ALTER TABLE [dbo].[DimReseller] CHECK CONSTRAINT [FK_DimReseller_DimGeography]
GO

# [FK_FactCallCenter_DimDate]

In [0]:
ALTER TABLE [dbo].[FactCallCenter]  WITH CHECK ADD  CONSTRAINT [FK_FactCallCenter_DimDate] FOREIGN KEY([DateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactCallCenter] CHECK CONSTRAINT [FK_FactCallCenter_DimDate]
GO

# [FK_FactCurrencyRate_DimCurrency]

In [0]:
ALTER TABLE [dbo].[FactCurrencyRate]  WITH CHECK ADD  CONSTRAINT [FK_FactCurrencyRate_DimCurrency] FOREIGN KEY([CurrencyKey])
REFERENCES [dbo].[DimCurrency] ([CurrencyKey])
GO
ALTER TABLE [dbo].[FactCurrencyRate] CHECK CONSTRAINT [FK_FactCurrencyRate_DimCurrency]
GO

# [FK_FactCurrencyRate_DimDate]

In [0]:
ALTER TABLE [dbo].[FactCurrencyRate]  WITH CHECK ADD  CONSTRAINT [FK_FactCurrencyRate_DimDate] FOREIGN KEY([DateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactCurrencyRate] CHECK CONSTRAINT [FK_FactCurrencyRate_DimDate]
GO

# [FK_FactFinance_DimAccount]

In [0]:
ALTER TABLE [dbo].[FactFinance]  WITH CHECK ADD  CONSTRAINT [FK_FactFinance_DimAccount] FOREIGN KEY([AccountKey])
REFERENCES [dbo].[DimAccount] ([AccountKey])
GO
ALTER TABLE [dbo].[FactFinance] CHECK CONSTRAINT [FK_FactFinance_DimAccount]
GO

# [FK_FactFinance_DimDate]

In [0]:
ALTER TABLE [dbo].[FactFinance]  WITH CHECK ADD  CONSTRAINT [FK_FactFinance_DimDate] FOREIGN KEY([DateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactFinance] CHECK CONSTRAINT [FK_FactFinance_DimDate]
GO

# [FK_FactFinance_DimDepartmentGroup]

In [0]:
ALTER TABLE [dbo].[FactFinance]  WITH CHECK ADD  CONSTRAINT [FK_FactFinance_DimDepartmentGroup] FOREIGN KEY([DepartmentGroupKey])
REFERENCES [dbo].[DimDepartmentGroup] ([DepartmentGroupKey])
GO
ALTER TABLE [dbo].[FactFinance] CHECK CONSTRAINT [FK_FactFinance_DimDepartmentGroup]
GO

# [FK_FactFinance_DimOrganization]

In [0]:
ALTER TABLE [dbo].[FactFinance]  WITH CHECK ADD  CONSTRAINT [FK_FactFinance_DimOrganization] FOREIGN KEY([OrganizationKey])
REFERENCES [dbo].[DimOrganization] ([OrganizationKey])
GO
ALTER TABLE [dbo].[FactFinance] CHECK CONSTRAINT [FK_FactFinance_DimOrganization]
GO

# [FK_FactFinance_DimScenario]

In [0]:
ALTER TABLE [dbo].[FactFinance]  WITH CHECK ADD  CONSTRAINT [FK_FactFinance_DimScenario] FOREIGN KEY([ScenarioKey])
REFERENCES [dbo].[DimScenario] ([ScenarioKey])
GO
ALTER TABLE [dbo].[FactFinance] CHECK CONSTRAINT [FK_FactFinance_DimScenario]
GO

# [FK_FactInternetSales_DimCurrency]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimCurrency] FOREIGN KEY([CurrencyKey])
REFERENCES [dbo].[DimCurrency] ([CurrencyKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimCurrency]
GO

# [FK_FactInternetSales_DimCustomer]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimCustomer] FOREIGN KEY([CustomerKey])
REFERENCES [dbo].[DimCustomer] ([CustomerKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimCustomer]
GO

# [FK_FactInternetSales_DimDate]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimDate] FOREIGN KEY([OrderDateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimDate]
GO

# [FK_FactInternetSales_DimDate1]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimDate1] FOREIGN KEY([DueDateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimDate1]
GO

# [FK_FactInternetSales_DimDate2]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimDate2] FOREIGN KEY([ShipDateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimDate2]
GO

# [FK_FactInternetSales_DimProduct]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimProduct] FOREIGN KEY([ProductKey])
REFERENCES [dbo].[DimProduct] ([ProductKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimProduct]
GO

# [FK_FactInternetSales_DimPromotion]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimPromotion] FOREIGN KEY([PromotionKey])
REFERENCES [dbo].[DimPromotion] ([PromotionKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimPromotion]
GO

# [FK_FactInternetSales_DimSalesTerritory]

In [0]:
ALTER TABLE [dbo].[FactInternetSales]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSales_DimSalesTerritory] FOREIGN KEY([SalesTerritoryKey])
REFERENCES [dbo].[DimSalesTerritory] ([SalesTerritoryKey])
GO
ALTER TABLE [dbo].[FactInternetSales] CHECK CONSTRAINT [FK_FactInternetSales_DimSalesTerritory]
GO

# [FK_FactInternetSalesReason_DimSalesReason]

In [0]:
ALTER TABLE [dbo].[FactInternetSalesReason]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSalesReason_DimSalesReason] FOREIGN KEY([SalesReasonKey])
REFERENCES [dbo].[DimSalesReason] ([SalesReasonKey])
GO
ALTER TABLE [dbo].[FactInternetSalesReason] CHECK CONSTRAINT [FK_FactInternetSalesReason_DimSalesReason]
GO

# [FK_FactInternetSalesReason_FactInternetSales]

In [0]:
ALTER TABLE [dbo].[FactInternetSalesReason]  WITH CHECK ADD  CONSTRAINT [FK_FactInternetSalesReason_FactInternetSales] FOREIGN KEY([SalesOrderNumber], [SalesOrderLineNumber])
REFERENCES [dbo].[FactInternetSales] ([SalesOrderNumber], [SalesOrderLineNumber])
GO
ALTER TABLE [dbo].[FactInternetSalesReason] CHECK CONSTRAINT [FK_FactInternetSalesReason_FactInternetSales]
GO

# [FK_FactProductInventory_DimDate]

In [0]:
ALTER TABLE [dbo].[FactProductInventory]  WITH CHECK ADD  CONSTRAINT [FK_FactProductInventory_DimDate] FOREIGN KEY([DateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactProductInventory] CHECK CONSTRAINT [FK_FactProductInventory_DimDate]
GO

# [FK_FactProductInventory_DimProduct]

In [0]:
ALTER TABLE [dbo].[FactProductInventory]  WITH CHECK ADD  CONSTRAINT [FK_FactProductInventory_DimProduct] FOREIGN KEY([ProductKey])
REFERENCES [dbo].[DimProduct] ([ProductKey])
GO
ALTER TABLE [dbo].[FactProductInventory] CHECK CONSTRAINT [FK_FactProductInventory_DimProduct]
GO

# [FK_FactResellerSales_DimCurrency]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimCurrency] FOREIGN KEY([CurrencyKey])
REFERENCES [dbo].[DimCurrency] ([CurrencyKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimCurrency]
GO

# [FK_FactResellerSales_DimDate]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimDate] FOREIGN KEY([OrderDateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimDate]
GO

# [FK_FactResellerSales_DimDate1]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimDate1] FOREIGN KEY([DueDateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimDate1]
GO

# [FK_FactResellerSales_DimDate2]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimDate2] FOREIGN KEY([ShipDateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimDate2]
GO

# [FK_FactResellerSales_DimEmployee]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimEmployee] FOREIGN KEY([EmployeeKey])
REFERENCES [dbo].[DimEmployee] ([EmployeeKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimEmployee]
GO

# [FK_FactResellerSales_DimProduct]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimProduct] FOREIGN KEY([ProductKey])
REFERENCES [dbo].[DimProduct] ([ProductKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimProduct]
GO

# [FK_FactResellerSales_DimPromotion]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimPromotion] FOREIGN KEY([PromotionKey])
REFERENCES [dbo].[DimPromotion] ([PromotionKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimPromotion]
GO

# [FK_FactResellerSales_DimReseller]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimReseller] FOREIGN KEY([ResellerKey])
REFERENCES [dbo].[DimReseller] ([ResellerKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimReseller]
GO

# [FK_FactResellerSales_DimSalesTerritory]

In [0]:
ALTER TABLE [dbo].[FactResellerSales]  WITH CHECK ADD  CONSTRAINT [FK_FactResellerSales_DimSalesTerritory] FOREIGN KEY([SalesTerritoryKey])
REFERENCES [dbo].[DimSalesTerritory] ([SalesTerritoryKey])
GO
ALTER TABLE [dbo].[FactResellerSales] CHECK CONSTRAINT [FK_FactResellerSales_DimSalesTerritory]
GO

# [FK_FactSalesQuota_DimDate]

In [0]:
ALTER TABLE [dbo].[FactSalesQuota]  WITH CHECK ADD  CONSTRAINT [FK_FactSalesQuota_DimDate] FOREIGN KEY([DateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactSalesQuota] CHECK CONSTRAINT [FK_FactSalesQuota_DimDate]
GO

# [FK_FactSalesQuota_DimEmployee]

In [0]:
ALTER TABLE [dbo].[FactSalesQuota]  WITH CHECK ADD  CONSTRAINT [FK_FactSalesQuota_DimEmployee] FOREIGN KEY([EmployeeKey])
REFERENCES [dbo].[DimEmployee] ([EmployeeKey])
GO
ALTER TABLE [dbo].[FactSalesQuota] CHECK CONSTRAINT [FK_FactSalesQuota_DimEmployee]
GO

# [FK_FactSurveyResponse_CustomerKey]

In [0]:
ALTER TABLE [dbo].[FactSurveyResponse]  WITH CHECK ADD  CONSTRAINT [FK_FactSurveyResponse_CustomerKey] FOREIGN KEY([CustomerKey])
REFERENCES [dbo].[DimCustomer] ([CustomerKey])
GO
ALTER TABLE [dbo].[FactSurveyResponse] CHECK CONSTRAINT [FK_FactSurveyResponse_CustomerKey]
GO

# [FK_FactSurveyResponse_DateKey]

In [0]:
ALTER TABLE [dbo].[FactSurveyResponse]  WITH CHECK ADD  CONSTRAINT [FK_FactSurveyResponse_DateKey] FOREIGN KEY([DateKey])
REFERENCES [dbo].[DimDate] ([DateKey])
GO
ALTER TABLE [dbo].[FactSurveyResponse] CHECK CONSTRAINT [FK_FactSurveyResponse_DateKey]
GO

# [dbo].[usp_test]

In [0]:
/****** Object:  StoredProcedure [dbo].[usp_test]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	create procedure [dbo].[usp_test] as 
	begin 
	select 1
	end 
GO

# [dbo].[usp_test1]

In [0]:
/****** Object:  StoredProcedure [dbo].[usp_test1]    Script Date: 25-05-2023 18:33:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	create procedure [dbo].[usp_test1] as 
	begin 
	select 1 as test
	end 
GO

# [ddlDatabaseTriggerLog]

In [0]:
/****** Object:  DdlTrigger [ddlDatabaseTriggerLog]    Script Date: 25-05-2023 18:33:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [ddlDatabaseTriggerLog] ON DATABASE 
FOR DDL_DATABASE_LEVEL_EVENTS AS 
BEGIN
    SET NOCOUNT ON;

    DECLARE @data XML;
    DECLARE @schema sysname;
    DECLARE @object sysname;
    DECLARE @eventType sysname;

    SET @data = EVENTDATA();
    SET @eventType = @data.value('(/EVENT_INSTANCE/EventType)[1]', 'sysname');
    SET @schema = @data.value('(/EVENT_INSTANCE/SchemaName)[1]', 'sysname');
    SET @object = @data.value('(/EVENT_INSTANCE/ObjectName)[1]', 'sysname') 

    IF @object IS NOT NULL
        PRINT '  ' + @eventType + ' - ' + @schema + '.' + @object;
    ELSE
        PRINT '  ' + @eventType + ' - ' + @schema;

    IF @eventType IS NULL
        PRINT CONVERT(nvarchar(max), @data);

    INSERT [dbo].[DatabaseLog] 
        (
        [PostTime], 
        [DatabaseUser], 
        [Event], 
        [Schema], 
        [Object], 
        [TSQL], 
        [XmlEvent]
        ) 
    VALUES 
        (
        GETDATE(), 
        CONVERT(sysname, CURRENT_USER), 
        @eventType, 
        CONVERT(sysname, @schema), 
        CONVERT(sysname, @object), 
        @data.value('(/EVENT_INSTANCE/TSQLCommand)[1]', 'nvarchar(max)'), 
        @data
        );
END;
GO
DISABLE TRIGGER [ddlDatabaseTriggerLog] ON DATABASE
GO

# [AdventureWorks]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [AdventureWorks] SET  READ_WRITE 
GO